substitutions:
  devicename: sonoff_dualr3
  long_devicename: Sonoff DualR3

esphome:
  name: $devicename
  platform: ESP32 
  board: esp32dev
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: light
#  ap:
#    ssid: !secret wifi_ssid
#    password: !secret wifi_password

captive_portal:
  
api:
  password: !secret hass_api

ota:
  password: !secret hass_api

web_server:
  port: 80

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 4800
  parity: NONE
  stop_bits: 2

sensor:
  - platform: bl0939
    update_interval: 5s
    voltage:
      name: '$long_devicename Voltage'
    current_1:
      name: '$long_devicename Current 1'
    current_2:
      name: '$long_devicename Current 2'
    active_power_1:
      name: '$long_devicename Active Power 1'

    active_power_2:
      name: '$long_devicename Active Power 2'
      on_value_range:
      - above: 10.0
        then:
        - logger.log: "$long_devicename Power above 10.0 W"
        - switch.turn_on: sw1
      - below: 10.0
        then:
        - logger.log: "$long_devicename Power below 10.0W"  
        - switch.turn_off: sw1    
    energy_1:
      name: '$long_devicename Energy 1'
    energy_2:
      name: '$long_devicename Energy 2'
    energy_total:
      name: '$long_devicename Energy Total'

output:
  - platform: gpio
    pin: GPIO27
    id: relay1
  - platform: gpio
    pin: GPIO14
    id: relay2

switch:
  - platform: output
    name: "$long_devicename - relay 1"
    output: relay1
    id: sw1
  - platform: output
    name: "$long_devicename - relay 2"
    output: relay2
    id: sw2

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$long_devicename button"
    on_press:
      - logger.log: "$long_devicename button"
      - switch.toggle: sw1
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: "$long_devicename switch 1"
    on_press:
      - logger.log: "$long_devicename switch 1"
      - switch.toggle: sw1
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    name: "$long_devicename switch 2"
    on_press:
      - logger.log: "$long_devicename switch 2"
      - switch.toggle: sw2
